### ISSUE TITLE
Enquiry for using the ahk

### ISSUE THREAD

**Issue by lee015328** [DaRealFreak/bns-macros#1]
Hi there im a Bns player from tw server and i saw that you have BnS - WR Lightning.ahk for Warden, however when i used it without meddling with any settings written in the code, i still fail to use the ahk effectively in the game. Its not as "one button" as i thought it would be, was hoping u would gimme a hand to use the ahk, since imo i think the coding is great but maybe is me who lacked the bigbrain to use the ahk. Tqvm

**Comment by DaRealFreak** [comment]
since it checks your user interface to see if a skill is available you'll have to change the ```Utility.GetColor(x,y) == "color_code"``` lines to match your user interface.
since every script is including the utility.ahk you can use the F1 key at the right positions to retrieve the color code/coordinates but it still requires a basic level of ahk knowledge
